name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
    - run: flutter config --enable-web
    - name: Install dependencies
      run: flutter pub get --no-example
    - name: Build web app
      run: flutter build web --no-source-maps --web-renderer=canvaskit
    - name: Deploy web app
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
